//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPSystemWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ApplTable
    {
        public int AppId { get; set; }
        [Required]
        public int UserId { get; set; }
        [Required]
        public int LoanId { get; set; }
        [Required]
        public string UserMob { get; set; }
        [Required]
        public string UserAdhaar { get; set; }
        [Required]
        public Nullable<decimal> LoanAmt { get; set; }
        [Required]
        public string AppStatus { get; set; }
    }
}
